/**
 * AUTO-GENERATED BY scripts/generate-http-route-constants.mjs
 * Source: contracts/http-routes.json
 * Do not edit by hand — run: node scripts/generate-http-route-constants.mjs
 */

export const USER_SERVICE_PREFIXES = [

] as const
