/**
 * AUTO-GENERATED BY scripts/generate-http-route-constants.mjs
 * Source: contracts/http-routes.json
 * Do not edit by hand — run: node scripts/generate-http-route-constants.mjs
 */

export const EDGE_ONLY_RULES = [
  '/api/search',
  '/api/book',
  '/api/chapters',
  '/api/content',
  '/api/batch/content',
] as const

export const DIRECT_RULES = [
  '/api/search',
  '/api/sources',
  '/api/source-packages',
  '/api/book',
  '/api/chapters',
  '/api/content',
  '/api/batch/content',
  '/api/bookshelf',
  '/api/groups',
  '/api/replace_rules',
  '/ws/',
] as const
