import { onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useRouter } from 'vue-router'
import { useMessage } from '@/composables/useMessage'
import { useSettingsStore } from '@/stores/settings'
import { useSourceBuilderDebugFormState } from '@/composables/source-builder/useSourceBuilderDebugFormState'
import { useSourceBuilderPreviewState } from '@/composables/source-builder/useSourceBuilderPreviewState'
import {
  useSourceBuilderDebugSnapshots,
} from '@/composables/source-builder/useSourceBuilderDebugSnapshots'
import { useSourceBuilderDebugPageActions } from '@/composables/source-builder/useSourceBuilderDebugPageActions'
import { useSourceBuilderFetchSession } from '@/composables/source-builder/useSourceBuilderFetchSession'
import { useSourceBuilderRunOperations } from '@/composables/source-builder/useSourceBuilderRunOperations'
import { useSourceBuilderSummaries } from '@/composables/source-builder/useSourceBuilderSummaries'
import { useSourceBuilderValidationRefine } from '@/composables/source-builder/useSourceBuilderValidationRefine'
import { useSourceBuilderRuntimeGovernance } from '@/composables/source-builder/useSourceBuilderRuntimeGovernance'
import { useSourceBuilderDebugViewEffects } from '@/composables/source-builder/useSourceBuilderDebugViewEffects'

export function useSourceBuilderDebugView() {
  const router = useRouter()
  const { success, warning } = useMessage()
  const settingsStore = useSettingsStore()
  const {
    sourcePackagesLoading,
    sourcePackageImporting,
    sourcePackageDetailLoading,
    sourceBuildRunning,
    sourcePackages,
    sourcePackageDetail,
    sourceBuildPreview,
    sourceBuildPreviewSummary,
  } = storeToRefs(settingsStore)

  const {
    bookCurl,
    chapterCurl,
    searchCurl,
    siteEntryCurl,
    searchKeyword,
    sourceId,
    sourceName,
    tagsText,
    fetchMode,
    fetchProvider,
    fetchServiceUrl,
    fetchEngine,
  } = useSourceBuilderDebugFormState()
  const {
    lastFetchDebug,
    previewPackage,
    previewPackageJson,
    previewDiagnostics,
    restoredDebugSnapshot,
    currentPackage,
    currentPackageJson,
    applyDebugSnapshot,
  } = useSourceBuilderPreviewState({
    sourcePackageDetail,
    sourceBuildPreviewSummary,
    bookCurl,
    chapterCurl,
    searchCurl,
    searchKeyword,
  })
  const {
    debugSnapshots,
    debugSnapshotSummary,
    loadDebugSnapshots,
    pushDebugSnapshot,
    restoreDebugSnapshot,
    clearDebugSnapshots,
  } = useSourceBuilderDebugSnapshots({
    onRestore: applyDebugSnapshot,
  })
  const {
    runtimeGovernanceLoading,
    runtimeGovernanceActionLoading,
    currentRuntimeSourceId,
    currentRuntimeSourceHealth,
    currentRuntimeGovernanceSummary,
    runtimeOverviewSummary,
    runtimeGovernanceSuggestions,
    refreshRuntimeGovernance,
    saveRuntimeSnapshot,
    exportRuntimeSnapshot,
    importRuntimeSnapshot,
    resetCurrentRuntimeState,
  } = useSourceBuilderRuntimeGovernance({
    currentPackage,
    sourceId,
  })
  const fetchSessionState = useSourceBuilderFetchSession({
    currentPackage,
    currentPackageJson,
    previewDiagnostics,
    getValidationReport: () => validationReport.value,
    fetchMode,
    fetchProvider,
    fetchServiceUrl,
    fetchEngine,
    pushDebugSnapshot,
  })
  const {
    fetchSessionKey,
    sessionCookiesText,
    sessionHeadersText,
    sessionLabel,
    sessionTtlSeconds,
    sessionLoading,
    currentFetchSession,
    fetchHtmlPreview,
    rawFetchHtmlPreview,
    fetchHtmlViewMode,
    fetchHtmlUrl,
    fetchHtmlMethod,
    fetchHtmlBody,
    fetchHtmlForceRefresh,
    fetchHtmlLoading,
    fetchHtmlError,
    fetchSessionSummary,
    fetchHtmlPreviewSummary,
    rawFetchHtmlPreviewSummary,
    fetchHtmlCompareSummary,
    importFetchSession,
    loadFetchSession,
    previewFetchHtml,
    clearFetchState,
  } = fetchSessionState
  const runOperations = useSourceBuilderRunOperations({
    currentPackage,
    lastFetchDebug,
  })
  const {
    runSearchQuery,
    runTargetUrl,
    runResult,
    runSearchDetailResult,
    runChaptersResult,
    runLoading,
    runExecutionProfileSummary,
    runSearchResultItems,
    runSummary,
    runSuggestedActions,
    runSearchDetailSummary,
    runSearchDetailSuggestedActions,
    runChapterResultItems,
    runChaptersSummary,
    runChaptersSuggestedActions,
    runOperation,
    runSearchAndValidateDetail,
    runDetailValidation,
    runDetailAndChaptersValidation,
    clearRunState,
  } = runOperations
  const validationRefine = useSourceBuilderValidationRefine({
    currentPackage,
    currentPackageJson,
    previewPackage,
    previewPackageJson,
    previewDiagnostics,
    fetchMode,
    fetchProvider,
    searchKeyword,
    fetchSessionKey,
    fetchHtmlPreview,
    lastFetchDebug,
    buildSnapshotContext: () => ({
      sourceLabel: previewPackage.value
        ? `${previewPackage.value.source.name} (${previewPackage.value.source.id})`
        : currentPackage.value
          ? `${currentPackage.value.source.name} (${currentPackage.value.source.id})`
          : undefined,
      sessionKey: fetchSessionKey.value.trim() || undefined,
      bookCurl: bookCurl.value,
      chapterCurl: chapterCurl.value,
      searchCurl: searchCurl.value,
      searchKeyword: searchKeyword.value,
    }),
    pushDebugSnapshot,
  })
  const {
    validateSearchQuery,
    validateBookUrl,
    validateTocUrl,
    validateChapterUrl,
    validationReport,
    validationLoading,
    structuredHints,
    freeTextHints,
    refineLoading,
    refineAutoActions,
    refineAppliedHints,
    refineChanges,
    aiAssistLoading,
    aiAssistSummary,
    aiAssistOpsLeaderboard,
    aiAssistOpsRegressionTop,
    aiAssistOpsRecommendedActions,
    validationStepSummary,
    refineSuggestions,
    requestAiAssist,
    requestAiAssistAndRefine,
    applyRecommendedAction,
    applyRecommendedActionAndRefine,
    validateCurrentPackage,
    applyRefineSuggestion,
    applyRefineSuggestionAndRefine,
    refineCurrentPackage,
    hasStructuredHints,
    applySnapshot: applyValidationSnapshot,
    clearValidationRefineState,
  } = validationRefine

  const { previewDiagnosticsItems } = useSourceBuilderDebugViewEffects({
    restoredDebugSnapshot,
    applyValidationSnapshot,
    applyFetchSnapshot: fetchSessionState.applySnapshot,
    lastFetchDebug,
    currentPackage,
    sourceBuildPreview,
    previewPackage,
    previewPackageJson,
    previewDiagnostics,
    validateBookUrl,
    validateChapterUrl,
    runTargetUrl,
    fetchHtmlUrl,
    runSearchQuery,
    searchKeyword,
    sourceBuildPreviewSummary,
  })
  const {
    currentDiagnosticsItems,
    currentPreviewSummary,
    fetchDebugSummary,
    searchProfileSummary,
    fetchProfileSummary,
  } = useSourceBuilderSummaries({
    currentPackage,
    previewDiagnostics,
    sourceBuildPreviewDiagnosticsItems: previewDiagnosticsItems,
    lastFetchDebug,
  })
  const {
    refreshPackages,
    buildFromSamples,
    importPreviewPackage,
    selectPackage,
    clearPreview,
    goBack,
  } = useSourceBuilderDebugPageActions({
    router,
    refreshSourcePackages: settingsStore.refreshSourcePackages,
    refreshRuntimeGovernance,
    buildFromSamplesOptions: {
      settingsStore,
      bookCurl,
      chapterCurl,
      searchCurl,
      siteEntryCurl,
      searchKeyword,
      sourceId,
      sourceName,
      tagsText,
      fetchMode,
      fetchProvider,
      fetchServiceUrl,
      fetchEngine,
      fetchSessionKey,
      structuredHints,
      hasStructuredHints,
      freeTextHints,
      previewPackage,
      previewPackageJson,
      previewDiagnostics,
      validationReport,
      lastFetchDebug,
      fetchHtmlPreview,
      pushDebugSnapshot,
      success,
      warning,
    },
    importPreviewOptions: {
      currentPackage,
      currentPackageJson,
      importSourcePackage: settingsStore.importSourcePackage,
      success,
      warning,
    },
    selectPackageOptions: {
      loadSourcePackageDetail: settingsStore.loadSourcePackageDetail,
    },
    clearPreviewOptions: {
      clearSourceBuildPreview: settingsStore.clearSourceBuildPreview,
      previewPackage,
      previewPackageJson,
      previewDiagnostics,
      runResult,
      runSearchDetailResult,
      runChaptersResult,
      lastFetchDebug,
      clearFetchState,
      clearRunState,
      clearValidationRefineState,
    },
  })

  async function buildValidateAndAutoRefine() {
    const built = await buildFromSamples()
    if (!built || !currentPackage.value) {
      warning('未生成可用规则包，无法继续自动流程')
      return
    }
    if (!validateSearchQuery.value.trim() && searchKeyword.value.trim()) {
      validateSearchQuery.value = searchKeyword.value.trim()
    }
    await validateCurrentPackage()
    await requestAiAssistAndRefine()
  }

  onMounted(async () => {
    loadDebugSnapshots()
    await refreshPackages()
  })

  return {
    sourcePackagesLoading,
    sourcePackageImporting,
    sourcePackageDetailLoading,
    sourceBuildRunning,
    sourcePackages,
    sourceBuildPreviewSummary,
    currentPreviewSummary,
    currentPackageJson,
    currentDiagnosticsItems,
    currentPackage,
    currentRuntimeSourceId,
    currentRuntimeSourceHealth,
    currentRuntimeGovernanceSummary,
    runtimeOverviewSummary,
    runtimeGovernanceSuggestions,
    runtimeGovernanceLoading,
    runtimeGovernanceActionLoading,
    searchProfileSummary,
    fetchProfileSummary,
    validationStepSummary,
    fetchDebugSummary,
    bookCurl,
    chapterCurl,
    searchCurl,
    siteEntryCurl,
    searchKeyword,
    sourceId,
    sourceName,
    tagsText,
    fetchMode,
    fetchProvider,
    fetchServiceUrl,
    fetchEngine,
    fetchSessionKey,
    sessionCookiesText,
    sessionHeadersText,
    sessionLabel,
    sessionTtlSeconds,
    sessionLoading,
    currentFetchSession,
    fetchSessionSummary,
    fetchHtmlPreview,
    fetchHtmlPreviewSummary,
    rawFetchHtmlPreview,
    rawFetchHtmlPreviewSummary,
    fetchHtmlCompareSummary,
    fetchHtmlViewMode,
    debugSnapshots,
    debugSnapshotSummary,
    fetchHtmlUrl,
    fetchHtmlMethod,
    fetchHtmlBody,
    fetchHtmlForceRefresh,
    fetchHtmlLoading,
    fetchHtmlError,
    structuredHints,
    freeTextHints,
    refineLoading,
    refineAutoActions,
    refineAppliedHints,
    refineChanges,
    aiAssistLoading,
    aiAssistSummary,
    aiAssistOpsLeaderboard,
    aiAssistOpsRegressionTop,
    aiAssistOpsRecommendedActions,
    refineSuggestions,
    validateSearchQuery,
    validateBookUrl,
    validateTocUrl,
    validateChapterUrl,
    validationReport,
    validationLoading,
    runSearchQuery,
    runTargetUrl,
    runResult,
    runSearchDetailResult,
    runChaptersResult,
    runLoading,
    runSummary,
    runSearchResultItems,
    runExecutionProfileSummary,
    runSuggestedActions,
    runSearchDetailSummary,
    runSearchDetailSuggestedActions,
    runChaptersSummary,
    runChapterResultItems,
    runChaptersSuggestedActions,
    buildFromSamples,
    buildValidateAndAutoRefine,
    importFetchSession: () => importFetchSession(lastFetchDebug),
    loadFetchSession,
    previewFetchHtml: () => previewFetchHtml(lastFetchDebug),
    restoreDebugSnapshot,
    clearDebugSnapshots,
    importPreviewPackage,
    refreshPackages,
    refreshRuntimeGovernance,
    saveRuntimeSnapshot,
    exportRuntimeSnapshot,
    importRuntimeSnapshot,
    resetCurrentRuntimeState,
    selectPackage,
    validateCurrentPackage,
    applyRefineSuggestion,
    applyRefineSuggestionAndRefine,
    requestAiAssist,
    requestAiAssistAndRefine,
    applyRecommendedAction,
    applyRecommendedActionAndRefine,
    refineCurrentPackage,
    runOperation,
    runSearchAndValidateDetail,
    runDetailValidation,
    runDetailAndChaptersValidation,
    clearPreview,
    goBack,
  }
}
