[package]
name = "nexus-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Core traits, error types, and data models for Nexus"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
chrono.workspace = true
urlencoding = "2"
uuid.workspace = true
erased-serde = "0.4.10"
url.workspace = true
parking_lot.workspace = true

[features]
default = []
discovery = []
