export type ReaderToolbarEmits = {
  back: []
  toggleCatalog: []
  toggleSettings: []
  toggleDayNight: []
  toggleFullscreen: []
  toggleEyeCare: []
  toggleZenMode: []
  refresh: []
  prevChapter: []
  nextChapter: []
  openSourcePicker: []
  openBookInfo: []
  toggleDecoder: [enabled: boolean]
  openDecoderSettings: []
}
