/**
 * AUTO-GENERATED BY scripts/generate-http-route-constants.mjs
 * Source: contracts/http-routes.json
 * Do not edit by hand — run: node scripts/generate-http-route-constants.mjs
 */

/** Allowed first path segments under /api/. */
export const API_ALLOWED_SEGMENTS = new Set([
  'batch',
  'book',
  'bookshelf',
  'chapters',
  'content',
  'explore',
  'groups',
  'health',
  'replace_rules',
  'search',
  'source-packages',
  'sources',
])

/** Paths that should be handled by edge cache. */
export const EDGE_HANDLED_PREFIXES = new Set([
  '/api/search',
  '/api/book',
  '/api/chapters',
  '/api/content',
  '/api/batch/content',
])
